apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config2
  # namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Argo CD HTML App2</title>
    </head>
    <body>
      <h1>hello opsbee technology</h1>
      <p>Deployment successful</p>
    </body>
    </html>
