apiVersion: v1
kind: Service
metadata:
  name: html-app-service2
  namespace: argocd-test-app
spec:
  type: NodePort
  selector:
    app: html-app2
  ports:
  - port: 80  
    targetPort: 80
    nodePort: 30095
    